/**
 * Homepage
 * Displays grid of topic cards
 */

import TopicCard from '@/components/TopicCard';
import { getTopicsData } from '@/lib/data';
import type { TopicCardData } from '@/lib/types';

export const revalidate = 300; // ISR: revalidate every 5 minutes

export default async function HomePage() {
  const topics = await getTopicsData();

  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-7xl">
        {/* Header */}
        <header className="mb-12">
          <h1 className="text-4xl font-bold tracking-tight mb-2">
            Reddit Perspective Cards
          </h1>
          <p className="text-lg text-muted-foreground">
            AI-generated summaries of trending Reddit discussions
          </p>
        </header>

        {/* Topics Grid */}
        {topics.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {topics.map((topic: TopicCardData) => (
              <TopicCard key={topic.slug} {...topic} />
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-muted-foreground text-lg">
              No topics available yet. Check back soon!
            </p>
          </div>
        )}

        {/* Footer */}
        <footer className="mt-16 pt-8 border-t text-center text-sm text-muted-foreground">
          <p>
            Data sourced from Reddit. Summaries generated by AI.{' '}
            <a
              href="https://github.com"
              className="text-primary hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              View source
            </a>
          </p>
        </footer>
      </div>
    </main>
  );
}
